### ISSUE TITLE
PublishTrimmed true run error

### ISSUE THREAD

**Issue by 3400442579** [irihitech/Semi.Avalonia#276]

**Comment by rabbitism** [comment]
Any log?

**Comment by 3400442579** [comment]
错误应用程序名称: Semi.Avalonia.Demo.Desktop.exe，版本: 1.0.0.0，时间戳: 0x6541164a
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.3570，时间戳: 0xfaa05682
异常代码: 0xe0434352
错误偏移量: 0x0013d982
错误进程 ID: 0x58d4
错误应用程序启动时间: 0x01da23277b07368c
错误应用程序路径: F:\Downloads\Semi.Avalonia-main\Semi.Avalonia-main\demo\Semi.Avalonia.Demo.Desktop\bin\Release\net7.0\publish\win-x86\Semi.Avalonia.Demo.Desktop.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: 069b9c3d-164a-4c4f-939b-7d9e91623815
错误程序包全名: 
错误程序包相对应用程序 ID: 



Application: Semi.Avalonia.Demo.Desktop.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for avares://Semi.Avalonia/Themes/Light/_index.axaml (baseUri: avares://Semi.Avalonia/Themes/Index.axaml), make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(IServiceProvider , Uri, Uri )
   at Avalonia.Markup.Xaml.Styling.ResourceInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.ResourceInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost)
   at Avalonia.Controls.ResourceDictionary.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost)
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost)
   at Avalonia.Styling.Styles.InternalAdd(IList, IResourceHost )
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T, Int32)
   at Avalonia.Collections.AvaloniaList`1.Add(T)
   at Avalonia.Styling.Styles.Add(IStyle)
   at Semi.Avalonia.Demo.App.!XamlIlPopulate(IServiceProvider, App) in F:\Downloads\Semi.Avalonia-main\Semi.Avalonia-main\demo\Semi.Avalonia.Demo\App.axaml:line 1
   at Semi.Avalonia.Demo.App.!XamlIlPopulateTrampoline(App)
   at Semi.Avalonia.Demo.App.Initialize() in F:\Downloads\Semi.Avalonia-main\Semi.Avalonia-main\demo\Semi.Avalonia.Demo\App.axaml.cs:line 12
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode )
   at Semi.Avalonia.Demo.Desktop.Program.Main(String[]) in F:\Downloads\Semi.Avalonia-main\Semi.Avalonia-main\demo\Semi.Avalonia.Demo.Desktop\Program.cs:line 14

**Comment by joseph-mckee** [comment]
Same thing, can't publish to trimmed single file. v11.0.6 and 11.1.0-beta1. Works fine untrimmed though.

Application: NetworkToolkitModern.App.exe
CoreCLR Version: 7.0.1624.6629
.NET Version: 7.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for avares://Semi.Avalonia/Themes/Light/_index.axaml (baseUri: avares://Semi.Avalonia/Themes/Index.axaml), make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(IServiceProvider , Uri, Uri )
   at Avalonia.Markup.Xaml.Styling.ResourceInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.ResourceInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost)
   at Avalonia.Controls.ResourceDictionary.OnAddOwner(IResourceHost)
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost)
   at Avalonia.Styling.Styles.InternalAdd(IList, IResourceHost )
   at Avalonia.Styling.Styles.OnCollectionChanged(Object , NotifyCollectionChangedEventArgs)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T, Int32)
   at NetworkToolkitModern.App.App.!XamlIlPopulate(IServiceProvider, App) in C:\Users\joseph\OneDrive - Default Directory\Documents\source\repos\NetworkToolkitModern\NetworkToolkitModern.App\App.axaml:line 14
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at NetworkToolkitModern.App.Program.Main(String[]) in C:\Users\joseph\OneDrive - Default Directory\Documents\source\repos\NetworkToolkitModern\NetworkToolkitModern.App\Program.cs:line 15

**Comment by rabbitism** [comment]
I will take a look
